name: Choice Test Workflow
on:
  workflow_dispatch:
    inputs:
      general-repo:
        type: string
        description: "Repository to checkout for a general deployment. Required when 'general' deployment is picked, is ignored otherwise."
        default: ""
      general-branch:
        type: string
        description: "Branch to checkout for a general deployment. Required when 'general' deployment is picked, is ignored otherwise."
        default: ""
      general-command:
        type: string
        description: "Command to run for a general deployment. Required when 'general' deployment is picked, is ignored otherwise."
        default: ""
      bundle-command:
        type: string
        description: "Command to run for a bundle deployment. Required when 'bundle' deployment is picked, is ignored otherwise."
        default: ""

jobs:
  run-workflow:
    runs-on: ubuntu-latest  # Or choose an appropriate runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # This step checks out your repository.

      - name: Validate inputs
        run: |
          general_deployment=false
          if [[ -n "${{ inputs.general-repo }}" && -n "${{ inputs.general-branch }}" && -n "${{ inputs.general-command }}" ]]; then
            general_deployment=true
          fi
          
          bundle_deployment=false
          if [[ -n "${{ inputs.bundle-command }}" ]]; then
            bundle_deployment=true
          fi
          
          if [[ "$general_deployment" == "$bundle_deployment" ]]; then
            if [[ "$general_deployment" == "false" ]]; then
              echo "Parameters must only be given for one of 'general' or 'bundle' deployment type, not both.
              exit 1
            fi
          fi
          
          echo $general_deployment
          echo $bundle_deployment
#      - name: Checkout Repo
#        if: ${{ inputs.deployment-type == 'general' }}
#        uses: actions/checkout@v4
#        with:
#          repository: ${{ inputs.general-repo }}
#          ref: ${{ inputs.general-branch }}
#
#      - name: List Directory and Run Command
#        if: ${{ inputs.deployment-type == 'general' }}
#        run: |
#          ls *
#          eval "${{ inputs.general-command }}"
#
#      - name: Run Bundle Command
#        if: ${{ inputs.deployment-type == 'bundle' }}
#        run: |
#          eval "${{ inputs.bundle-command }}"