name: Reusable Workflow Dispatcher

on:
  workflow_dispatch:

jobs:
  run_reusable_workflow:
    concurrency:
      group: msargent-dev-reusable-workflow-queue # Shared concurrency group name
      cancel-in-progress: false     # Queue instead of canceling
    uses: ./.github/workflows/concurrency-test.yml
