name: Concurrency Test

on:
  workflow_call:

concurrency:
  group: msargent-dev-concurrency
  cancel-in-progress: false

jobs:
  run-and-sleep:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "sleeping"
          sleep 120
