name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          json_output=$(yq e -o=json '.include = .data | del(.data)' fake-config.yml | tr -d '\n')
          echo "output is $json_output"
          echo "::set-output name=matrix::$json_output"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}

    steps:
      - run: echo ${{ matrix.project }}
      - run: echo ${{ matrix.config }}