name: Test Echo Trick
on:
  workflow_dispatch:

jobs:
  call-starter-workflow:
    runs-on: ubuntu-latest  # Or choose an appropriate runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This step checks out your repository.

    - name: Test echoing all variables
      run: |
        a=hello
        b=world
        c=hooray
        d=this
        e=worked
        
        echo "vars should appear below this line"
        ( set -o posix; set | grep '^[a-z].*=' )
        ( set -o posix; set | grep '^[a-z].*=' ) >> $GITHUB_ENV

    - name: Test using vars from the env
      run: |
        echo ${{ env.c }} ${{ env.d }} ${{ env.e }}