name: Test TAF Workflow
on:
  workflow_dispatch:
    inputs:
        name:
          type: choice
          description: What to run
          options: 
          - workflowA.yml
          - workflowB.yml

jobs:
  call-starter-workflow:
    runs-on: ubuntu-latest  # Or choose an appropriate runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This step checks out your repository.

    - name: Move Action To Known Location
      run: |
        mkdir deploy-action
        mv ${{ github.event.inputs.name }} deploy-action/action.yml
      working-directory: ${{ github.workspace }}
    
    - name: Execute Starter Workflow
      uses: ./deploy-action  # Use the local directory where the workflow is placed
